nodeLinker: pnp

# Enable PnP features
pnpMode: strict

# Better performance
compressionLevel: mixed

# Modern features
enableImmutableInstalls: false

# PnP compatibility
supportedArchitectures:
  os: [current]
  cpu: [current]