# Yarn 4.9.2 + PnP Configuration for Portfolio
nodeLinker: pnp

# PnP Mode - loose is more compatible for development
pnpMode: strict

# Performance optimizations
compressionLevel: mixed
enableGlobalCache: true
enableMirror: false

# Development settings
enableImmutableInstalls: false
enableInlineBuilds: false

# Platform support
supportedArchitectures:
  os: [current]
  cpu: [current]

# Prisma PnP compatibility - Essential for database functionality
packageExtensions:
  '@prisma/client@*':
    dependencies:
      prisma: '*'
      resolve: '*'
    peerDependencies:
      prisma: '*'
  'prisma@*':
    dependencies:
      resolve: '*'

# TypeScript PnP support is built-in to Yarn 4.9.2

# PnP fallbacks for generated dependencies
pnpFallbackMode: dependencies-only
